# Generated by Django 5.0.3 on 2024-04-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='dname',
            field=models.CharField(max_length=100),
        ),
    ]
